name: Analyzer Scheduled Job

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 */5 * * *' # Every 5 hours

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'
      - name: Run analyzer script
        env:
            GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "This job runs every 5 hours."
          cd analyzer
          go run .
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
