name: Crawler Scheduled Job

on:
  schedule:
    - cron: '0 1 * * *' # 9am UTC+8 is 1am UTC

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'
      - name: Run your script
        run: |
          echo "This job runs only at 9am UTC+8 and not on push events."
          cd crawler
          go run .
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
