name: Scheduled Job Only

on:
  schedule:
    - cron: '0 1 * * *' # 9am UTC+8 is 1am UTC
  push:
    branches-ignore:
      - '**'

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'
      - name: Run your script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "This job runs only at 9am UTC+8 and not on push events."
          cd automation
          go run .
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add automation/data/*
          if ! git diff --cached --quiet; then
            git commit -m "Update data folder from scheduled job"
            git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
            git push origin HEAD:${{ github.ref }}
          else
            echo "No changes to commit."
          fi
