name: Scheduled Job

on:
  schedule:
    - cron: '0 0 */1 * *'

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'
      - name: Run crawler script
        working-directory: ./crawler
        run: |
          echo "Running crawler..."
          go run .
      - name: Run analyzer script
        working-directory: ./analyzer
        env:
            GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "Running analyzer..."
          go run .
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Purge CDN Cache
        run: |
          curl "https://purge.jsdelivr.net/gh/maplestoria/PurifyJandan@main/blocked_users.json"